config/routes.rb
Rails.application.routes.draw do
  get 'users/new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users,  only: [:show,]

  get '/contracts/select', to: 'contracts#select'
  get '/contracts/explain', to: 'contracts#explain'
  post '/contracts/explained', to: 'contracts#explained'
  post '/contracts/generate', to: 'contracts#generate'
  post '/contracts/edit', to: 'contracts#editpost'
  post '/contracts/newclause', to: 'contracts#newclause'
  post '/contracts/deleteclause', to: 'contracts#deleteclause'
  get '/contracts/:id/generatepdf', to: 'contracts#generatepdf'
  get '/contracts/:id/printable', to: 'contracts#printable'
  get 'users/contracts/upload', to: 'contracts#upload'
  post 'users/contracts/upload_file', to: 'contracts#upload_file'
  resources :contracts, only: [:show, :create, :new, :edit]


  resources :terms,  only: [:show,]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
end

app/models/contract.rb
# == Schema Information
#
# Table name: contracts
#
#  id               :bigint           not null, primary key
#  borrower_address :string
#  borrower_name    :string
#  clauses          :integer          default("{}"), is an Array
#  contract_type    :string
#  data             :json
#  interest_rate    :float
#  lender_address   :string
#  lender_name      :string
#  loan_amount      :bigint
#  loan_duration    :integer
#  name             :string
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  user_id          :bigint
#
# Indexes
#
#  index_contracts_on_user_id                 (user_id)
#  index_contracts_on_user_id_and_created_at  (user_id,created_at)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Contract < ApplicationRecord
  belongs_to :user
  validates :user_id, presence: true
end

app/controllers/contracts_controller.rb
include ActionView::Helpers::TextHelper
include ERB::Util

require 'digest/md5'
require 'pdf-reader'

class ContractsController < ApplicationController

  skip_before_action :verify_authenticity_token

  def new

  end

  def create

  end

  def explain

  end

  def explained
    @explained = simple_format html_escape params[:text]
    Term.find_each do |term|
      @explained.gsub! /#{term.text}/i, '<a href="/terms/' + term.id.to_s + '">' + term.text + "</a>"
    end
  end

  def show
    @contract = Contract.find(params[:id])

    @clauses = []
    @contract.clauses.each do |id|
        @clauses << Clause.find(id);
    end
  end

  def generatepdf
    pdf = PdfGenerator.new(Contract.find(params[:id]))
    pdf.generate()
    send_data pdf.render,
      filename: "contract.pdf",
      type: "application/pdf",
      disposition: "inline"
  end

  def printable
    @contract = Contract.find(params[:id])

    @clauses = []
    @contract.clauses.each do |id|
        @clauses << Clause.find(id);
    end
  end

  def select
  end

  def edit
    @contract = Contract.find(params[:id])
  end

  def editpost
    contract = Contract.find(params[:id])
    data = contract.data
    contract.name = params[:name]
    data[:name] = params[:name]
    contract.lender_address = params[:lender_address]
    data[:lender_address] = params[:lender_address]
    contract.borrower_address = params[:borrower_address]
    data[:borrower_address] = params[:borrower_address]
    contract.borrower_name = params[:borrower_name]
    data[:borrower_name] = params[:borrower_name]
    contract.lender_name = params[:lender_name]
    data[:lender_name] = params[:lender_name]
    contract.loan_amount = params[:loan_amount]
    data[:loan_amount] = params[:loan_amount]
    contract.interest_rate = params[:interest_rate]
    data[:interest_rate] = params[:interest_rate]
    contract.loan_duration = params[:loan_duration]
    data[:loan_duration] = params[:loan_duration]
    contract.user = current_user

    all_parameters = generate_clauses(contract)
    contract.data = data
    store_clauses_as_data(contract, all_parameters)



    contract.save!
    redirect_to contract_path(contract.id)
  end

  def generate
    # For now this is hard coded to create loan contract only
    # Refactor in the future if we decide to work further on this
    contract = Contract.new
    data = {}
    contract.contract_type = 'Loan'
    data[:contract_type] = 'Loan'

    # Common data
    contract.name = params[:name]
    data[:name] = params[:name]

    # Non common data
    contract.lender_address = params[:lender_address]
    data[:lender_address] = params[:lender_address]
    contract.borrower_address = params[:borrower_address]
    data[:borrower_address] = params[:borrower_address]
    contract.borrower_name = params[:borrower_name]
    data[:borrower_name] = params[:borrower_name]
    contract.lender_name = params[:lender_name]
    data[:lender_name] = params[:lender_name]
    contract.loan_amount = params[:loan_amount]
    data[:loan_amount] = params[:loan_amount]
    contract.interest_rate = params[:interest_rate]
    data[:interest_rate] = params[:interest_rate]
    contract.loan_duration = params[:loan_duration]
    data[:loan_duration] = params[:loan_duration]
    contract.user = current_user

    contract.data = data

    all_parameters = generate_clauses(contract)
    store_clauses_as_data(contract, all_parameters)

    contract.save!
    redirect_to contract_path(contract.id)
  end

  def upload

  end

  def upload_file
    if File.extname(params[:file].tempfile) != ".pdf"
      raise "Unsupported file type"
    end
    reader = PDF::Reader.new(params[:file].tempfile)
    data = reader.info
    if data[:contract_type] == "Loan"
      id = upload_loan_contract(data)
    end
    redirect_to contract_path(id)
  end

  def newclause
    contract = Contract.find(params[:id])
    newclause = Clause.create(text: params[:newtext], name: contract.name + '_custom_' + params[:newclauseid], explanation_text: params[:newexplanation], custom: true)
    newclause.save!
    contract.clauses << newclause.id
    
    data = contract.data
    data_clauses = JSON.parse(data["clauses"])
    data_clauses[(data_clauses.length + 1).to_s] = {
      "custom" => newclause.custom,
      "template_name" => newclause.template_name,
      "text" => newclause.text,
      "explanation_text" => newclause.explanation_text,
      "name" => newclause.name,
      "parameters" => nil
    }
    data["clauses"] = data_clauses.to_json
    contract.data = data
    contract.save!
    redirect_to contract_path(contract.id)
  end

  def deleteclause
    contract = Contract.find(params[:id])
    clause = Clause.delete(params[:clauseid])
    contract.clauses.delete_at(params[:contractclauseid].to_i - 1)

    contract.save!
    redirect_to contract_path(contract.id)
  end

  private

  def generate_clauses(contract)
    all_parameters = {}
    custom_clauses = []
    contract.clauses.each do |clause|
      current_clause = Clause.find(clause)
      # Only destroy template clauses when you edit
      unless current_clause.custom
        current_clause.destroy
      else
        custom_clauses << current_clause.id
      end
    end
    all_clauses = []
    base_template = ClauseTemplate.find_by(name: 'loan_base')
    parameters = [contract.lender_name, contract.borrower_name, contract.lender_address,
                  contract.borrower_address]
    text = base_template.replace_merge_tags(parameters)
    clause = Clause.create(text: text, name: contract.name + 'loan_base',
                           explanation_text: base_template.explanation_text,
                           template_name: base_template.name, custom: false)
    all_parameters[clause.id] = parameters
    all_clauses << clause.id

    template = ClauseTemplate.find_by(name: 'loan_amount')
    parameters = ['%d' % [contract.loan_amount]]
    text = template.replace_merge_tags(parameters)
    clause = Clause.create(text: text, name: contract.name + 'loan_amount',
                           explanation_text: template.explanation_text,
                           template_name: template.name, custom: false)
    all_parameters[clause.id] = parameters
    all_clauses << clause.id

    template = ClauseTemplate.find_by(name: 'loan_term')
    parameters = ['%d' % [contract.loan_duration]]
    text = template.replace_merge_tags(parameters)
    clause = Clause.create(text: text, name: contract.name + 'loan_duration',
                           explanation_text: template.explanation_text,
                           template_name: template.name, custom: false)
    all_clauses << clause.id
    all_parameters[clause.id] = parameters

    template = ClauseTemplate.find_by(name: 'interest_rate')
    parameters = ['%0.2f' % [contract.interest_rate]]
    text = template.replace_merge_tags(parameters)
    clause = Clause.create(text: text, name: contract.name + 'interest_rate',
                           explanation_text: template.explanation_text,
                           template_name: template.name, custom: false)
    all_clauses << clause.id
    all_parameters[clause.id] = parameters

    template = ClauseTemplate.find_by(name: 'legally_binding')
    text = template.replace_merge_tags([])
    clause = Clause.create(text: text, name: contract.name + 'legally_binding',
                           explanation_text: template.explanation_text,
                           template_name: template.name, custom: false)
    all_clauses << clause.id
    all_parameters[clause.id] = parameters

    custom_clauses.each do |clause|
      all_clauses << clause
    end
    contract.update_attribute(:clauses, all_clauses)
    all_parameters
  end

  def store_clauses_as_data(contract, all_parameters)
    clauses = {}
    count = 1
    contract.clauses.each do |c|
      current_clause = Clause.find(c)
      clauses[count.to_s] = {
        "custom" => current_clause.custom,
        "template_name" => current_clause.template_name,
        "text" => current_clause.text,
        "explanation_text" => current_clause.explanation_text,
        "name" => current_clause.name,
        "parameters" => all_parameters[current_clause.id]
      }
      count += 1
    end
    new_data = contract.data
    new_data["clauses"] = clauses.to_json
    contract.update_attribute(:data, new_data)
    contract.save
  end

  def upload_loan_contract(data)
    contract = Contract.new
    contract.name = data[:name]
    contract.contract_type = 'Loan'
    contract.data = data

    all_clauses = []

    contract.lender_address = data[:lender_address]
    contract.borrower_address = data[:borrower_address]
    contract.borrower_name = data[:borrower_name]
    contract.lender_name = data[:lender_name]
    contract.loan_amount = data[:loan_amount]
    contract.interest_rate = data[:interest_rate]
    contract.loan_duration = data[:loan_duration]
    contract.user = current_user

    json_hash = JSON.parse(data[:clauses])
    json_hash.each do |data|
      clause_data = data[1]
      if clause_data["custom"]
        newclause = Clause.create(text: clause_data["text"], name: clause_data["name"], explanation_text: clause_data["explanation_text"], custom: true)
        newclause.save!
        all_clauses << newclause.id
      else
        template = ClauseTemplate.find_by(name: clause_data["template_name"])
        if template.nil?
          newclause = Clause.create(text: clause_data["text"], name: clause_data["name"], explanation_text: clause_data["explanation_text"], custom: true)
          newclause.save!
          all_clauses << newclause.id
        else
          text = template.replace_merge_tags(clause_data["parameters"])
          newclause = Clause.create(text: text, name: clause_data["name"], explanation_text: clause_data["explanation_text"], custom: false)
          newclause.save!
          all_clauses << newclause.id
        end
      end
    end

    contract.clauses = all_clauses

app/helpers/contracts_helper.rb
module ContractsHelper
end

app/views/contracts/_contract.html.erb
<li id="contract-<%= contract.id %>">
  <span class="name"><%= link_to contract.name, contract %></span>
  <span class="timestamp">
    Created <%= time_ago_in_words(contract.created_at) %> ago.
  </span>
</li>

app/views/contracts/edit.html.erb
<% provide(:title, 'Edit Contract') %>
<h1>Edit Loan Contract</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_tag('/contracts/edit', :method => "post") do %>
      <%= hidden_field_tag :id, @contract.id %>

      <%= label_tag(:name, "Contract name:") %>
      <%= text_field_tag(:name, @contract.name) %>

      <%= label_tag(:language, "Preferred language for agreement") %></br>
      <%= radio_button_tag(:language, "english") %><%= label_tag(:language_english, "English") %>
      <%= radio_button_tag(:language, "chinese") %><%= label_tag(:language_chinese, "Chinese") %>
      <%= radio_button_tag(:language, "tamil") %><%= label_tag(:language_tamil, "Tamil") %>
      </br></br>
      <%= label_tag(:lender_address, "Lender address") %>
      <%= text_field_tag(:lender_address, @contract.lender_address) %>

      <%= label_tag(:borrower_address, "Borrower address") %>
      <%= text_field_tag(:borrower_address, @contract.borrower_address) %>

      <%= label_tag(:borrower_name, "Borrower name:") %>
      <%= text_field_tag(:borrower_name, @contract.borrower_name) %>

      <%= label_tag(:lender_name, "Lender name:") %>
      <%= text_field_tag(:lender_name, @contract.lender_name) %>

      <%= label_tag(:loan_amount, "Loan amount (in SGD):") %>
      <%= text_field_tag(:loan_amount, @contract.loan_amount) %>

      <%= label_tag(:loan_duration, "Loan duration (in months):") %>
      <%= text_field_tag(:loan_duration, @contract.loan_duration) %>

      <%= label_tag(:interest_rate, "Annual loan interest rate (in percentage):") %>
      <%= text_field_tag(:interest_rate, @contract.interest_rate) %>

      <%= submit_tag("Edit") %>
    <% end %>
  </div>
</div>

app/views/contracts/explain.html.erb
<% provide(:title, 'Explain Contract') %>
<h1>Explain Contract</h1>

<!--<div> Insert contract text: </div>-->
  <%= form_tag('/contracts/explained', :method => "post") do %>
      <div class="form-group">
        <label for="text">Insert contract text:</label>
        <textarea class="form-control" id="text" name="text">

        </textarea>
      </div>
    <button type="submit" id="explain" class="btn btn-primary">Explain</button>
  <% end %>

app/views/contracts/explained.html.erb
<% provide(:title, 'Explain Contract') %>
<h1>Explained Contract</h1>



<p>
    <%= raw @explained %>
</p>

app/views/contracts/new.html.erb
<% provide(:title, 'New Contract') %>
<h1>Create Loan Contract</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_tag('/contracts/generate', :method => "post") do %>
      <%= label_tag(:name, "Contract name:") %>
      <%= text_field_tag(:name, "", class: 'form-control') %>

      <%= label_tag(:language, "Preferred language for agreement") %></br>
      <%= radio_button_tag(:language, "english") %><%= label_tag(:language_english, "English") %>
      <%= radio_button_tag(:language, "chinese") %><%= label_tag(:language_chinese, "Chinese") %>
      <%= radio_button_tag(:language, "tamil") %><%= label_tag(:language_tamil, "Tamil") %>
      </br></br>
      <%= label_tag(:lender_address, "Lender address") %>
      <%= text_field_tag(:lender_address, "", class: 'form-control') %>

      <%= label_tag(:borrower_address, "Borrower address") %>
      <%= text_field_tag(:borrower_address, "", class: 'form-control') %>

      <%= label_tag(:borrower_name, "Borrower name:") %>
      <%= text_field_tag(:borrower_name, "", class: 'form-control') %>

      <%= label_tag(:lender_name, "Lender name:") %>
      <%= text_field_tag(:lender_name, "", class: 'form-control') %>

      <%= label_tag(:loan_amount, "Loan amount (in SGD):") %>
      <%= text_field_tag(:loan_amount, "", class: 'form-control') %>

      <%= label_tag(:loan_duration, "Loan duration (in months):") %>
      <%= text_field_tag(:loan_duration, "", class: 'form-control') %>

      <%= label_tag(:interest_rate, "Annual loan interest rate (in percentage):") %>
      <%= text_field_tag(:interest_rate, "", class: 'form-control') %>

      <%= submit_tag("Create", class: 'btn btn-primary') %>
    <% end %>
  </div>
</div>

app/views/contracts/printable.html.erb
<% provide(:title, @contract.name) %>

<div class="input-group">

  <%= link_to contract_path(@contract.id) do %>
    <button type="button" class="btn btn-primary">Back</button>
  <% end %>

    <button type="button" class="btn btn-success">Print</button>
</div>
<center><h1>LOAN AGREEMENT</center>


<p>This Loan Agreement (the “<b>Agreement</b>”) is entered into on  ____________________ (the "<b>Effective Date</b>), by and between <%= @contract.lender_name %>, with an address of <%= @contract.lender_address %> (the “Lender”) and <%= @contract.borrower_name %>, with an address of <%= @contract.borrower_address %>, (the “<b>Borrower</b>”), collectively “<b>the Parties.</b>”</p>

<p>WHEREAS, Borrower desires to borrow a fixed amount of money; and</p>
<p>WHEREAS, Lender agrees to lend a fixed amount of money;</p></p>
<p>IN CONSIDERATION of, the mutual promises, covenants, and conditions contained herein, the Parties agree as follows:</p>

<ol>
    <% @clauses.each do |clause| %>
    <li><%= clause.text %></li>
    <% end %>
</ol>

app/views/contracts/select.html.erb
<!--
<div class="card" style="width: 18rem;">
  <img src="/house.png" class="card-img-top" />
  <div class="card-body">
    <h5 class="card-title">Loans</h5>
    <p class="card-text">Borrowing money.</p>

    <%= link_to '/contracts/new', class: "btn btn-primary stretched-link" do %>
        <h3>Loans</h3>
    <% end %>
  </div>
</div>

<div class="media position-relative">
  <img src="..." class="mr-3" alt="...">
  <div class="media-body">
    <h5 class="mt-0">Media with stretched link</h5>
    <p>Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.</p>
    <a href="#" class="stretched-link">Go somewhere</a>
  </div>
</div>
-->

<div>

    <div class="page-header"><h1> Select a type of contract </h1></div>
    <div class="row is-flex">
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
            <div class="box text-center thumbnail">
                <div class="box text-center caption contracttype">
                    <%= link_to '/contracts/new' do %>
                        <img src="/house.png"/>
                        <h3>Loans</h3>
                    <% end %>
                </div>
            </div>

        </div>
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
            <div class="box text-center thumbnail">
                <div class="box text-center caption contracttype">
                    <%= link_to '/contracts/new' do %>
                        <img src="/house.png"/>
                        <h3>Sales</h3>
                    <% end %>
                </div>
            </div>

        </div>
    </div>

</div>

app/views/contracts/show.html.erb
<% provide(:title, @contract.name) %>

<div class="input-group">

  <%= link_to edit_contract_path(@contract.id) do %>
    <button type="button" class="btn btn-primary">Edit</button>
  <% end %>

  <%= link_to '/contracts/' + @contract.id.to_s + '/printable' do %>
    <button type="button" class="btn btn-success">Generate</button>
  <% end %>

  <button type="button" class="btn btn-success">Add Clause</button>
  <%= link_to '/contracts/' + @contract.id.to_s + '/generatepdf' do %>
    <button type="button" class="btn btn-success">Generate</button>
  <% end %>
</div>
<center><h1><%= @contract.name %></h1></center>
<h2>Contract Details</h2>
<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th scope="col">Type</th>
      <th scope="col">Details</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">Contract type:</th>
      <td><%= @contract.contract_type %></td>
    </tr>
    <tr>
      <th scope="row">Lender Name:</th>
      <td><%= @contract.lender_name %></td>
    </tr>
    <tr>
      <th scope="row">Borrower Name:</th>
      <td><%= @contract.borrower_name %></td>
    </tr>
    <tr>
      <th scope="row">Lender Address:</th>
      <td><%= @contract.lender_address %></td>
    </tr>
    <tr>
      <th scope="row">Borrower Address:</th>
      <td><%= @contract.borrower_address %></td>
    </tr>
    <tr>
      <th scope="row">Loan Amount:</th>
      <td><%= @contract.loan_amount %></td>
    </tr>
    <tr>
      <th scope="row">Loan Duration:</th>
      <td><%= @contract.loan_duration %> months</td>
    </tr>
    <tr>
      <th scope="row">Interest Rate:  </th>
      <td><%= @contract.interest_rate %></td>
    </tr>
  </tbody>
</table>

<h2>Additional clauses</h2>
<% counter = 0 %>
<table id='employee-table' class="table table-hover">
  <thead>
    <tr>
      <th>ID</th>
      <th>Clause</th>
      <th>Explanation</th>
      <th>Action</th>
    </tr>
  </thead>

  <tbody>
    <% @clauses.each do |clause| %>
      <% counter += 1 %>
      <tr>
        <td><%= counter %></td>
        <td><%= clause.text %></td>
        <td><%= clause.explanation_text %></td>
        <td>
          <%= form_tag('/contracts/deleteclause', :method => "post") do %>
          <%= hidden_field_tag :id, @contract.id %>
          <%= hidden_field_tag :clauseid, clause.id %>
          <%= hidden_field_tag :contractclauseid, counter %>
          <%= submit_tag "Delete", class: 'btn btn-danger' %>
          <% end %>
        </td>
      </tr>

    <% end %>
    <% counter += 1 %>
    <%= form_tag('/contracts/newclause', :method => "post") do %>
    <%= hidden_field_tag :id, @contract.id %>
    <%= hidden_field_tag :newclauseid, counter %>
    <tr>
      <td> <%= counter %> </td>
      <td> <%= text_field_tag(:newtext, "", class: 'form-control') %> </td>
      <td> <%= text_field_tag(:newexplanation, "", class: 'form-control') %> </td>
      <td> <%= submit_tag "Add", class: 'btn btn-success' %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/contracts/upload.html.erb
<h1>File Upload</h1>

<%= form_with(url: {action: :upload_file}, multipart: true) do %>
  <%= file_field_tag 'file', :accept => 'application/pdf' %>
  <%= submit_tag "Upload" %>
<% end %>