config/routes.rb
Rails.application.routes.draw do
  get 'users/new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users,  only: [:show,]

  get '/contracts/select', to: 'contracts#select'
  get '/contracts/explain', to: 'contracts#explain'
  post '/contracts/explained', to: 'contracts#explained'
  post '/contracts/generate', to: 'contracts#generate'
  post '/contracts/edit', to: 'contracts#editpost'
  post '/contracts/newclause', to: 'contracts#newclause'
  post '/contracts/deleteclause', to: 'contracts#deleteclause'
  get '/contracts/:id/generatepdf', to: 'contracts#generatepdf'
  get '/contracts/:id/printable', to: 'contracts#printable'
  get 'users/contracts/upload', to: 'contracts#upload'
  post 'users/contracts/upload_file', to: 'contracts#upload_file'
  resources :contracts, only: [:show, :create, :new, :edit]


  resources :terms,  only: [:show,]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
end

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "Contract.IO", '/', id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home",   '/'  %></li>

            <% if logged_in? %>
              <li><%= link_to "Contracts", user_path(current_user) %></li>
              <li><%= link_to "New Contract", '/contracts/select' %></li>
              <li><%= link_to "Explain Contract", '/contracts/explain' %></li>
              <li><%= link_to "Log out", logout_path, method: :delete %></li>
            <% else %>
              <li><%= link_to "Log in", login_path %></li>
            <% end %>

          </ul>
        </nav>
      </div>
    </header>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>